[app]
name = "cmdb-demo"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8060"

[app.grpc]
host = "127.0.0.1"
port = "18060"


[mysql]
host = "127.0.0.1"
port = "3306"
database = "go_course"
username = "root"
password = "Murphy"

[mongodb]
endpoints = ["127.0.0.1:27017"]
username = "keyauth"
password = "Murphy"
database = "keyauth"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"