[app]
name = "cmdb-demo"
key  = "this is your app key"

[http]
host = "127.0.0.1"
port = "8840"

[grpc]
host = "127.0.0.1"
port = "18840"


[keyauth]
host = "127.0.0.1"
port = "18050"
client_id = "demo"
client_secret = "demo"


[mysql]
host = "127.0.0.1"
port = "3306"
database = "test"
username = "root"
password = "Murphy"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"